# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  bookify.api:
    build:
      context: "D:\\Projets\\Bookify"
      dockerfile: "src/Bookify.Api/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Bookify.Api.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "bookifyapi:dev"
    ports: []
    volumes:
    - "C:\\Users\\olive\\AppData\\Roaming\\Microsoft\\UserSecrets:/home/app/.microsoft/usersecrets"
    - "C:\\Users\\olive\\.nuget\\packages:/home/app/.nuget/packages"
    - "D:\\Projets\\Bookify\\src\\Bookify.Api:/app:rw"
    - "D:\\Projets\\Bookify:/src:rw"
    working_dir: "/app"
