name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  DOTNET_VERSION: "8.x"
  SOLUTION_PATH: "./Bookify.sln"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore ./Bookify.sln

      - name: Build
        run: dotnet build ./Bookify.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test ./Bookify.sln --configuration Release --no-restore --no-build

      - name: Publish
        run: dotnet publish ./Bookify.sln --configuration Release --no-restore --no-build
